version: "3.7"

services:
  densh:
    image: unclephil/densh:latest
    environment:
      - DENSH_CLUSTER_NAME=${CLUSTER_NAME}
      - DENSH_NOTIFIER=console
      - DENSH_APPRISE_URL=http://apprise:8000/notify
      - DENSH_APPRISE_TITLE=DenShBot ${CLUSTER_NAME}
      - DENSH_WEBHOOK_URL=https://elkprd01.intranet.etnic.be/densh/densh
      - DENSH_WEBHOOK_AUTH=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - notification
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  apprise:
    image: caronc/apprise
    environment:
      APPRISE_STATELESS_URLS: discord://.../...
    networks:
      - notification
    # ports:
    #   - 8000:8000
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

networks:
  notification: